version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
      MYSQL_USER: desafio
      MYSQL_PASSWORD: desafio
    networks:
      - desafio-net

  node-app:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - desafio-net
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - desafio-net
    depends_on:
      - node-app

networks:
  desafio-net:
    driver: bridge
